# Generated by Django 4.1.7 on 2023-03-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(null=True)),
                ('machine', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('is_passed', models.BooleanField(default=False, verbose_name='paseed')),
                ('is_failed', models.BooleanField(default=False, verbose_name='failed')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
