# Generated by Django 4.1.7 on 2023-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_instituion_name_user_institute_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(null=True)),
                ('task', models.CharField(max_length=150)),
                ('machine', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
