# Generated by Django 4.1.7 on 2023-04-05 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ukes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukes',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='passed'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(null=True)),
                ('brand', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('problem', models.CharField(max_length=350)),
                ('repair', models.CharField(max_length=350)),
                ('cust_name', models.CharField(max_length=150)),
                ('tech_name', models.CharField(max_length=150)),
                ('complain_num', models.CharField(max_length=150)),
                ('is_completed', models.BooleanField(default=False, verbose_name='completed')),
                ('is_continue', models.BooleanField(default=False, verbose_name='continue')),
                ('service_type', models.CharField(choices=[('EMG', 'Emergency'), ('NONEMG', 'Non-emergency'), ('CONTR', 'Contract'), ('INSTL', 'Install'), ('WRT', 'Warranty'), ('OTR', 'Other')], default='NONEMG', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
