# Generated by Django 4.1.7 on 2023-04-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ukes_is_passed_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('NON-EMERGENCY', 'Non-emergency'), ('CONTRACT', 'Contract'), ('INSTLALL', 'Install'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], default='NON-EMERGENCY', max_length=100),
        ),
    ]
