# Generated by Django 4.1.7 on 2023-04-12 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('NON-EMERGENCY', 'Non-emergency'), ('CONTRACT', 'Contract'), ('INSTALL', 'Install'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], default='NON-EMERGENCY', max_length=100),
        ),
        migrations.CreateModel(
            name='Sertifkalibrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(null=True)),
                ('file_name', models.CharField(max_length=150)),
                ('machine', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('pdf_file', models.FileField(upload_to='sertifkalibrasi/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
