# Generated by Django 4.1.7 on 2023-04-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_service_service_type_sertifkalibrasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertifkalibrasi',
            name='location',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
