# Generated by Django 4.1.7 on 2023-04-25 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sertifkalibrasi_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalibrasi',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='passed'),
        ),
        migrations.CreateModel(
            name='Sertifukes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=150)),
                ('file_name', models.CharField(max_length=150)),
                ('machine', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('pdf_file', models.FileField(upload_to='sertifukes/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
