# Generated by Django 4.1.7 on 2023-05-21 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(null=True)),
                ('period', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('hospital_unit', models.CharField(max_length=150)),
                ('xray_brand', models.CharField(max_length=150)),
                ('xray_type', models.CharField(max_length=150)),
                ('xray_serial', models.CharField(max_length=150)),
                ('calib_brand', models.CharField(max_length=150)),
                ('calib_type', models.CharField(max_length=150)),
                ('calib_serial', models.CharField(max_length=150)),
                ('ctrl_panel_cond', models.BooleanField(default=False)),
                ('cmd_arm_cond', models.BooleanField(default=False)),
                ('bucky_tbl_cond', models.BooleanField(default=False)),
                ('bucky_std_cond', models.BooleanField(default=False)),
                ('tube_std_cond', models.BooleanField(default=False)),
                ('generator_cond', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
